DISTVERSION=    2.10.0

PKGNAMESUFFIX=  210

COMMENT=        Visualization dashboards for OpenSearch

CONFLICTS=      opensearch-dashboards

DISTINFO=       ${.CURDIR}/distinfo

MASTERDIR=      ${.CURDIR}/../../textproc/opensearch-dashboards

.include "${MASTERDIR}/Makefile"
