PKGNAMESUFFIX=  210

COMMENT=	Visualization dashboards for OpenSearch

CONFLICTS=      opensearch-dashboards

MASTERDIR=      ${.CURDIR}/../../textproc/opensearch-dashboards

.include "${MASTERDIR}/Makefile"
